{{- if .Values.httpRoute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "onlyfangs.fullname" . }}
  labels:
    {{- include "onlyfangs.labels" . | nindent 4 }}
  {{- with .Values.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  backendRefs:
    - name: {{ include "onlyfangs.fullname" . }}
      port: {{ .Values.service.port }}
  {{- with .Values.httpRoute.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  hostnames:
    {{- toYaml .Values.httpRoute.hostnames | nindent 4 }}
  rules:
    - backendRefs:
        - name: {{ include "onlyfangs.fullname" . }}
          port: {{ .Values.service.port }}
      {{ with .Values.httpRoute.matches }}
      matches:
        {{- toYaml . | nindent 4 }}
      {{ end }}
{{- end }}
