// @generated automatically by Diesel CLI.

/// A module containing custom SQL type definitions
///
/// (Automatically generated by Diesel.)
pub mod sql_types {
    /// The `application_status` SQL type
    ///
    /// (Automatically generated by Diesel.)
    #[derive(diesel::query_builder::QueryId, Clone, diesel::sql_types::SqlType)]
    #[diesel(postgres_type(name = "application_status"))]
    pub struct ApplicationStatus;

    /// The `twitch_account_type` SQL type
    ///
    /// (Automatically generated by Diesel.)
    #[derive(diesel::query_builder::QueryId, Clone, diesel::sql_types::SqlType)]
    #[diesel(postgres_type(name = "twitch_account_type"))]
    pub struct TwitchAccountType;
}

diesel::table! {
    /// Representation of the `application_comments` table.
    ///
    /// (Automatically generated by Diesel.)
    application_comments (id) {
        /// The `id` column of the `application_comments` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `application_id` column of the `application_comments` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        application_id -> Int4,
        /// The `comment` column of the `application_comments` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        comment -> Text,
        /// The `twitch_user_id` column of the `application_comments` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        twitch_user_id -> Int4,
        /// The `twitch_username` column of the `application_comments` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        twitch_username -> Text,
        /// The `twitch_display_name` column of the `application_comments` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        twitch_display_name -> Text,
        /// The `twitch_profile_image_url` column of the `application_comments` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        twitch_profile_image_url -> Text,
        /// The `created_at` column of the `application_comments` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use super::sql_types::TwitchAccountType;
    use super::sql_types::ApplicationStatus;

    /// Representation of the `applications` table.
    ///
    /// (Automatically generated by Diesel.)
    applications (id) {
        /// The `id` column of the `applications` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `twitch_id` column of the `applications` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        twitch_id -> Int4,
        /// The `twitch_username` column of the `applications` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        twitch_username -> Text,
        /// The `twitch_display_name` column of the `applications` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        twitch_display_name -> Text,
        /// The `twitch_profile_image_url` column of the `applications` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        twitch_profile_image_url -> Text,
        /// The `twitch_account_type` column of the `applications` table.
        ///
        /// Its SQL type is `TwitchAccountType`.
        ///
        /// (Automatically generated by Diesel.)
        twitch_account_type -> TwitchAccountType,
        /// The `status` column of the `applications` table.
        ///
        /// Its SQL type is `ApplicationStatus`.
        ///
        /// (Automatically generated by Diesel.)
        status -> ApplicationStatus,
        /// The `reason` column of the `applications` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        reason -> Text,
        /// The `support_clip_url` column of the `applications` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        support_clip_url -> Text,
        /// The `follow_count` column of the `applications` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        follow_count -> Int4,
        /// The `connecting_ip_address` column of the `applications` table.
        ///
        /// Its SQL type is `Inet`.
        ///
        /// (Automatically generated by Diesel.)
        connecting_ip_address -> Inet,
        /// The `created_at` column of the `applications` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `updated_at` column of the `applications` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
        /// The `completed_at` column of the `applications` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        completed_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    /// Representation of the `health_check` table.
    ///
    /// (Automatically generated by Diesel.)
    health_check (id) {
        /// The `id` column of the `health_check` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `updated_at` column of the `health_check` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
    }
}

diesel::joinable!(application_comments -> applications (application_id));

diesel::allow_tables_to_appear_in_same_query!(application_comments, applications, health_check,);
